### ISSUE TITLE
Help wanted: how to understand buf lifetime on buf_ring ?

### ISSUE THREAD

**Issue by glenn-wang** [tokio-rs/io-uring#176]
I make a [udp echo server](https://github.com/glenn-wang/iou_udp)  using io_uring register_buf_ring refer to [register_buf_ring test demo](https://github.com/tokio-rs/io-uring/blob/master/io-uring-test/src/tests/register_buf_ring.rs)

Problem:
I register 2 bufs, expect `error: ENOBUFS` when processing the 3rd packet without calling `std::mem::drop(buf1)`. But the error not occur.

The [udp echo server](https://github.com/glenn-wang/iou_udp) is simple, whether my usage is wrong or there is a bug ?

```
Operating System: Ubuntu 22.04.1 LTS              
          Kernel: Linux 6.1.8-060108-generic
    Architecture: x86-64
```

@FrankReh would you have time to give a look at this problem ？

**Comment by FrankReh** [comment]
@glenn-wang 

In the future, you may want to provide a simpler example for a volunteer to look at a problem for you. You didn't create a minimal case that works vs not working. You didn't provide code that compiles on its own. You didn't make it easy to see what you had taken from my unit test and what you had changed and added.

But I was curious if I could figure this out. Especially because you said it was working and thought it shouldn't be working and you're using a newish feature of urings, the buf_ring. And it turns out, you're using another new feature, the multishot receive.

I've spent too much time writing up what I found and guessing what you thought should be happening and ended up deleting it all and starting over. So here it is.

You are creating a multi receive operation that will pick a buffer from the ring and always use 3 as the user_data field.

You then have a loop that blocks, waiting for at least one cqe to come in. You do some book keeping for the cqe, I don't know if that's right in all cases, but it works in how I was testing it.

Then you loop through the CQEs.

Your first block seems designed to handle the results of the echo response operation, the write. You recognize it because you use user_data values that are less than 2, so just 0 and 1. And in it you have a comment leading me to believe you think that is the right place to drop a buf_ring buffer. Well it's not. The buf_ring buffer was dropped automatically when it went out of scope at the bottom of the loop. Buf_ring buffers cannot be used for sending data safely unless you expressly keep the buffer from going out of scope until the operation is complete. You don't do that. You use the buffer's storage for parts of the write's msg and get away with it because the storage is not rewritten until the buffer is cycled through again, every 2nd time a UDP packet is received.

If you tested by flooding three UDP packets at a time before the loop could run, you would see the buf ring being exhausted. If the flood test were a little slower, you would notice that the data being sent back to the UDP client wasn't correct.

The second block in the CQE loop handles receiving a user_data 3 cqe, so a result from the multishot receive.

The cqe provides the buffer id that was picked, so 0 or 1. You create the buffer reference from that bid. You then use its parts to build up a msg that you will use to start a write operation at the bottom of the loop. You submit the write. And here  you don't seem to understand the buffer named my_buf goes out of scope. The my_buf type is designed to clean itself up. You, the user are not required to manually drop it.

The fact you use the bid as the user_data for the write should not make sense - there is no reason to. You could always just use a value of 0, or any value that wasn't 3, so you could differentiate the recv results from the write results. The user_data is a way of matching a cqe received with the sqe created at an earlier time.

So I want to say you can't really do what you are trying to do with that loop but it is possible, just with more code. At the bottom of the loop, you need some storage space for the data but make no allowance for keeping that storage alive while the write operation is in flight. So you are breaking the safety contract necessary by the unsafe block at line 281, where you push the write operation onto the submission queue. This is a common problem with the io-uring unsafe push operation. Lots of designers have not taken the unsafe contract to heart when they call it. I've seen it now four times myself and I'm very new to these projects.

You could go to pains to use more permanent storage. You could use a slab and use the slab indexes as the user_data field. The slab entry could be a simple byte array that you had copied the ingress buffer's data into. Or you design the slab to take ownership of the buf_ring buffer so it doesn't get dropped until you take it from the slab later, in the block where you handle the write CQEs. Either way, the slab entry gets released when the write's cqe is processed, so the data it was keeping live would outlive the in-flight write. Of course there are other ways not involving slabs, but the slab is a useful tool and happens to be used by the tokio-uring for just this purpose.

**Comment by glenn-wang** [comment]
@FrankReh 

Thank you very much for your patient reply and suggestions. I will digest and absorb the suggestions.

This project has no demo of udp server.  My purpose is to implement the following demo with Rust lang.  
https://github.com/axboe/liburing/blob/master/examples/io_uring-udp.c

Moreover，I really didn't realize that the buf was automatically dropped.
> You submit the write. And here you don't seem to understand the buffer named my_buf goes out of scope. The my_buf type  is designed to clean itself up. You, the user are not required to manually drop it.

**Comment by FrankReh** [comment]
A couple of things. You seem new to all this. Maybe you don't know Rust that well yet. Then my suggestion is to try and code anything you want, but don't use `unsafe`. In the code you copied and added to, there are lots of `unsafe` calls. `unsafe` should only be used when one knows a lot about the Rust borrow checker rules and have a good idea of memory management. The fact you didn't know how to interpret the code you copied from the unit test indicates that regular Rust is still a struggle.

So just read through Rust you find interesting, and teach yourself what every little bit of it does. When you see an `impl` that `Drops`, be curious what that means and ask yourself why the author wrote that. With any Rust code, one should ask what happens to a variable type when it goes out of scope.

When you copy a large part of code like that. It maybe isn't legally required to attribute where it comes from, but it's a nice courtesy.

When you get back to writing Rust code and using `unsafe` blocks in it. Document each as to how the code you are writing is maintaining the safety contract. Why should a reader believe it is safe, why are you resorting to `unsafe` and what do you know that the compiler doesn't that makes it actually safe.

The reason the compiler didn't help you know you were sending a buffer that was going out of scope was that you had wrapped the submit call in an `unsafe`.  Now you might say, well the io-uring author requires it is wrapped in `unsafe`. That would be correct. But in a language like Rust, then you should ask yourself why? Why did the author require the `unsafe` tag to that call? If you can't understand their reason, then when things start going wrong, you should first assume you don't understand enough. And highlight to anyone helping you where the `unsafe` blocks are.

The io-uring library, and even the tokio-ouring library, are not meant for people new to Rust. Rust is hard by itself at first. One could learn a lot just using the std library which is essentially all synchronous. Even the io-uring library is still all synchronous but it is providing the bindings for the asynchronous world of the Linux io_uring device and it requires `unsafe` programming. And asynchronous programming is harder. There is a lot to understand. There are a lot of user manuals to read in the liburing repo's man directory. Understanding what goes in an SQE and what comes back from the CQE, and how buffers are shared between the userland and the kernel takes some time. Actually you got quite far but it was your misunderstanding of buffer memory that tripped you up. The C language has no such complexity. All the heap memory is handled with manual calls like malloc and free. So a buffer could live a long time, outside of the scope where it was allocated - and C programmers make great use of that and also create bugs that are hard to find and great security holes.

Rust wants to protect you from yourself, and help, by freeing memory when it's handle goes out of scope. And it normally would not let you pass a pointer to that memory, or any address within it, to something that can outlive the scope ... unless you do those operations in an `unsafe` block.

So brush up on drop. See how the buf_ring buffer is added back to the kernel's buf_ring when the drop function is called. And learn to recognize where the compiler would put that drop function call.

And you probably shouldn't create issues with errors making it sound like a fundamental feature is broken and you shouldn't assume you may have uncovered a bug so quickly.

Maybe you could change the title of this issue, for posterity's sake. Something like, "Looking for help understanding buffer lifetimes".

Good luck. Thanks for being interested in Rust, mutlshot accept operations and buffer rings.
