### ISSUE TITLE
Fallocate len should have type `loff_t`

### ISSUE THREAD

**Issue by Xinkai** [tokio-rs/io-uring#27]
Hi,

`man 2 fallocate` says `len` should be an `off_t`, and this library implements that as an `u32`.

Related:
https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L331-L337

**Comment by quininer** [comment]
Thank you for your report.

Using `u32` here does not cause error, because `len` cannot be negative.

There are some interface definitions in `io-uring` syscall that are not completely consistent with `libc`. for example, the count of `libc::read` is `usize`, but it can only be `u32` in `io-uring`.

I have been thinking about whether to provide an interface similar to `libc`, even if they are not actually consistent.

**Comment by quininer** [comment]
Anyway, I do realize that u32 is not the best choice. but change it will break compatibility, so I will keep it until next version.

**Comment by Xinkai** [comment]
Thank for the reply.

https://github.com/torvalds/linux/blob/690e2aba7beb1ef06352803bea41a68a3c695015/fs/io_uring.c#L370-L376 <- where `fallocate` `len` and possibly others go.

The rust `libc` library does provide an `loff_t` type. Maybe we should use that instead, so we can stay as faithful to the kernel as possible.
