### ISSUE TITLE
Is AvailableQueue necessary?

### ISSUE THREAD

**Issue by Kestrer** [tokio-rs/io-uring#61]
Currently we have `squeue::AvailableQueue` and `cqueue::AvailableQueue` that represent a snapshot of the submission queue and completion queue respectively. But I don't think either are necessary: performance-wise, atomic loads and stores are incredibly cheap, and utility-wise there isn't much benefit in freezing the queue at a specific point in time, and if users wish to do that they can just cap it off at the length of the queue manually.

I think it would be a lot simpler if we got rid of them entirely, and made `CompletionQueue` implement `Iterator` and have the `push` method on `SubmissionQueue`.

**Comment by quininer** [comment]
I agree that `AvailableQueue` may not much performance advantage, but I don't think we need to get rid of it.

We can simply implement `push` for `SubmissionQueue` and implement `Iterator` for `CompletionQueue`, which does not conflict with `AvailableQueue`. but so far I haven't seen too many benefits to implement these. because we can always simply call `sq.available().push()` and `cq.available().next()`.

**Comment by Koxiaet** [comment]
I would like to get rid of it because it simplifies the API, and reduces the amount of work users have to do to learn how to use this library. It also reduces the maintainance cost - not having to maintain two sets of `capacity`/`len`/`is_empty`/`is_full` methods and keep their docs and tests in sync etc is a large benefit in my opinion. Also I find it's somewhat of a misnomer, "available queue" doesn't really accurately describe what it does.

**Comment by quininer** [comment]
These methods only have dozens of lines of code in total, and I don't think this is a heavy burden. If it is a burden, I will consider remove the `capacity`/`len`/`is_empty`/`is_full` methods of `SubmissionQueue`/`CompletionQueue`.

I didn't understand what problems the `AvailableQueue` caused.

**Comment by Koxiaet** [comment]
I suppose there aren't any problems, I just would like to have the simplest possible API :smiley:. If we're going to keep the type there's no point in removing those methods, they're useful.
